Feature: generalised functorialisation
thibautbenjamin/catt pull request #49
Opened 2024-04-20 10:15 UTC by regular-citizen

This PR implements the recursive machinery for running arbitrary depth functorialisation. It deprecates old functorialisation code and enables functorialisation w.r.t locally maximal variables of arbitrary codimension.

2024-04-22 14:46 UTC, regular-citizen commented
@thibautbenjamin ready for review

2024-05-14 14:12 UTC, thibautbenjamin requested changes
Review done. Mostly minor things but a few points that I am not entirely convinced with. Happy to discuss them in person whenever

2024-05-18 14:51 UTC, regular-citizen commented on lib/builtin.ml
> +let whisk n j k =
Not implementing this. Will deal in future PR when shuffling the functorialisation coherence code around

2024-05-18 14:51 UTC, regular-citizen commented
Implemented reviews

2024-05-18 14:52 UTC, regular-citizen commented
@thibautbenjamin can you merge?

2024-05-20 10:14 UTC, thibautbenjamin approved these changes

2024-05-20 10:14 UTC, merged

2024-05-20 10:15 UTC, thibautbenjamin commented
Done! I did squash and merge because the history wasn't very clean